env:
  global:
    - CC_TEST_REPORTER_ID

before_install:
  - gem update --system
  - gem --version

language: ruby
rvm:
- 2.5.0

before_script:
  - bundle exec rake db:create db:migrate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build


script:
  bundle exec rake testcode

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

cache: bundler

services:
  -postgresql
addons:
  postgresql: "9.4"
